### ISSUE TITLE
TextMate Coloring Should Control Background/Foreground

### ISSUE THREAD

**Issue by eliasvasylenko** [eclipse/tm4e#115]
The TextMate syntax colouring option should also control the background colour, as otherwise it will clash for people using dark themes.

**Comment by angelozerr** [comment]
I agree with you, but have you tried to switch to dark theme? The render is good no?

**Comment by eliasvasylenko** [comment]
Oh I see now, you have to select the dark theme in `General -> Appearance`.

I hadn't noticed this as I use the `Light` theme there. But at the same time I use the `Eclipse Color Theme` plugin to use a dark theme for syntax colouring. Would it be possible to allow selection of the TextMate dark theme and light theme manually rather than basing it on the IDE theme?

**Comment by mickaelistria** [comment]
> I hadn't noticed this as I use the Light theme there. But at the same
> time I use the Eclipse Color Theme plugin to use a dark theme for syntax
> colouring. Would it be possible to allow selection of the TextMate dark
> theme and light theme manually rather than basing it on the IDE theme?


Although having the ability to manually select the theme would be nice,
it's important to keep things usable for most users (who don't use Eclipse
Color Theme). Those users shouldn't have to manually change the TextMate
theme, and having the TextMate theme updated automatically according to the
IDE theme is great for them. Just make sure adding this option doesn't make
things harder.

**Comment by eliasvasylenko** [comment]
There could always be an `automatic` theme option selected by default. Regardless, I understand that none of this is priority work.

**Comment by angelozerr** [comment]
> Although having the ability to manually select the theme would be nice

I have started to develop something in the the UI preferences to support with theme associations:

![image](https://user-images.githubusercontent.com/1932211/27130731-cd68ece6-5107-11e7-9c66-99e8d424c18a.png)

Just find time to develop "New" button.

**Comment by angelozerr** [comment]
> The TextMate syntax colouring option should also control the background colour

@mickaelistria are you OK to override Styledtext#set*Color ?

**Comment by ainslec** [comment]
Continuing thread from #124.

The issue detailed there is not exactly the same as this issue. This issue is concerned with just background colo(u)r. My issue in #124 is about both background and foreground. For example, the monokai theme on Sublime uses RGB (248,248,242) for 'text' style. In TM4E's default monokai theme on Eclipse dark theme, it is RGB(131, 148, 150). This is not white, it is a muddy grey. Of course, I can use the preferences to override it to the correct RGB value, but if I do that for all text editors, I throw out the balance in all editors, not just the one editor I wish to fix.

The simplest approach is this. You can't tweak themed editors via the generic preference settings. A complete targetted theme can only be modified by another complete theme.

**Comment by angelozerr** [comment]
> The issue detailed there is not exactly the same as this issue. This issue is concerned with just background colo(u)r.

See my comment https://github.com/eclipse/tm4e/issues/115#issuecomment-308407094

**Comment by ainslec** [comment]
A little more information on this issue. I have managed to get my previous plugin working (with explicit grammar contribution and monokai style baked into the plugin). This worked in Neon, but now because of the background colour and foreground text colour being inherited from the generic text editor settings (per Eclipse theme) in Eclipse, Monokai is broken even in the case of this explicit mapping:

![hhhhhh9](https://user-images.githubusercontent.com/201870/28789667-3e2ec82a-761e-11e7-9201-2b6ceba11c63.png)

All colours are correct aside from the base text colour and background colour. This is enough to destroy the theme. It should look like this :

![image](https://user-images.githubusercontent.com/201870/28788806-5a91e79e-761a-11e7-9a10-5998fb4f51a3.png)

If the solution is to select "dark" as the Eclipse theme, firstly, the dark theme does not work on my computer. It is unspeakably ugly, and buggy too. Plus, I do not wish to have a dark theme, I just want a specific editor to be dark - because it suits the content. Even if I have to add a parameter to the plugin to enable non-inheritance of theme background and foreground colours, I'm fin with that so long as I can use a dark background editor (such as monokai) without the "dark" eclipse theme - which does not work on my computer.

**Comment by angelozerr** [comment]
> If the solution is to select "dark" as the Eclipse theme, firstly, the dark theme does not work on my computer. 

Yes it worked like this. Now each theme can configure background/foreground color. Here the result with Monokai with classic eclipse theme:

![image](https://user-images.githubusercontent.com/1932211/28858697-b055f75e-7752-11e7-9885-8c3d0bacead1.png)

Please note that I have improved Monokay by supporting underline.

You can see again problem with line selection. I don't know how to configure that? Any help are welcome.

**Comment by ainslec** [comment]
I updated to the new version and the background color is working exactly as expected. Yes, now the line color is the issue, especially as white text is very common on a dark background. But technically speaking, the background color and foreground text colour issue is fixed, and the line color issue is a new issue.

**Comment by ainslec** [comment]
Hello,

I'm sure you are aware of this, but you it is possible to set the line colour via the following dialog, although I think that TM4E should be configuring this per theme and not using the default per generic text editor :

![image](https://user-images.githubusercontent.com/201870/28875717-71761f3c-778e-11e7-8a7f-d95ba0976342.png)

I set the line colour to RGB(80,80,80) in this screenshot. I think the line colour, like the background colour should be part of the theme CSS. I would imagine it is the exact same mapping logic as you used for background colour in the last set of checkins, but I'm not an expert on CSS with regards to Eclipse.

**Comment by angelozerr** [comment]
I close this issue. See https://github.com/eclipse/tm4e/issues/126 for problem with line highlight
