### ISSUE TITLE
Theme / grammar association via preferences menu requires reload of text editor window

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#123]
When I change the the theme / style association in the preferences menu, it is not reflected in loaded editors (e.g. associate my grammar with monokai for Eclipse Dark theme).  I must close an editor then reload it. Changing theme associations should force refresh of all open editors.

**Comment by angelozerr** [comment]
Have you forced with hard coded your theme with TMPresentationReconciler#setThemeId ? If it that I think it's your problem. It should work?

**Comment by ainslec** [comment]
This is not a hand coded theme, this is using the preferences settings and a manually added .tmLanguage  file.

**Comment by angelozerr** [comment]
I think it worked, please wait for I finish https://github.com/eclipse/tm4e/issues/118

**Comment by angelozerr** [comment]
@ainslec please reinstall and tell me if it works since #118 is implemented..

**Comment by ainslec** [comment]
I have updated to the new version. The responses here are different to the responses in the other thread (this one is dealing with my grammar being added purely via the preferences menu, the other issue is regarding embedding via plugin).

The theming does not seem to work in my Eclipse correctly (because of Windows 7 I think) so I operate without Eclipse theming configured or else my Eclipse quickly allocates 5GB of memory for itself - another issue entirely). Anyway, here are my Eclipse theming options - you can see I have Eclipse theming disabled :

![ccxz](https://user-images.githubusercontent.com/201870/28789155-0d9fe3d0-761c-11e7-829e-d9523a914d4a.png)

I tried to simply just associate monokai with the grammar, but I don't understand the dialog. What I would expect to see is a default style (for all themes or Eclipse theming disabled), plus Textmate Theme overrides per Eclipse Theme. The dialog box does not show which Eclipse theme the grammar to theme mapping is applying to.

![gdfgfdg7](https://user-images.githubusercontent.com/201870/28789259-8338d9d0-761c-11e7-858b-3272acecebcc.png)

I can tell you that no matter what I try, I can't seem to use monokai theme (with dark background colour) unless themes are enabled in Eclipse, even though I can clearly see that tm4e IS colouring in the grammar. It's just a matter of letting the Eclipse settings (which is a white background in no theme mode) mess around with carefully balanced themes - which I don't believe should be the default behaviour.

**Comment by angelozerr** [comment]
> I tried to simply just associate monokai with the grammar, but I don't understand the dialog. 

Yes it's normal, I must finish this UI. Please be patient.

> What I would expect to see is a default textmate stylesheet (for all themes or Eclipse theming disabled), plus Textmate stylesheet overrides per Eclipse Theme. The dialog box does not show which Eclipse theme the grammar to theme mapping is applying to.

At first I had managed a mapping between eclipse theme and textmate theme for a grammar. But it was difficult to configure that (because there are several "Light" Eclipse themes liek classic, etc). That's why I have decided to categorize eclipse theme into : "Light", "Dark" themes. You can see that in the TextMate / Themes preferences

![image](https://user-images.githubusercontent.com/1932211/28798318-6bcf1cbe-7644-11e7-8b0d-79f5719af0fd.png)

So now the Grammar / theme associations shows which Theme you must use for Light Eclipse Theme and for Dark Eclipse theme. 

> unless themes (specifically the dark theme) are enabled in Eclipse,

Today you cannot configure Monokai for "Light" theme. I will se how to fix that.

> I don't believe the default text editor background and text color for any given theme should override the carefully balanced textmate themes (by default).

tm4e does nothing about background/foreground (it's eclipse IDE which manage that). Please wait for https://github.com/eclipse/tm4e/issues/115

**Comment by ainslec** [comment]
Thanks for the update. I will see how things go with #115.

Switch to theme is a nice option to have - I tried it out and it should work well for switching light themes (only). I'd just love to see monokai as an option under "light" themes for my grammar, and the ability to change background colour to dark even in Eclipse light themes. This is the last time I will repeat myself :-)

**Comment by angelozerr** [comment]
> Switch to theme is a nice option to have - I tried it out and it should work well for switching light themes (only). I'd just love to see monokai as an option under "light" themes for my grammar, and the ability to change background colour to dark even in Eclipse light themes. This is the last time I will repeat myself :-)

It should be fixed (almost), see my comments at https://github.com/eclipse/tm4e/issues/115#issuecomment-319570134

Can we close this issue?

**Comment by angelozerr** [comment]
> I tried to simply just associate monokai with the grammar, but I don't understand the dialog.

Now we have that:

![image](https://user-images.githubusercontent.com/1932211/28858850-d90aad92-7753-11e7-83de-64429b43f68c.png)

Is it more clear?

**Comment by ainslec** [comment]
Regarding the foreground window in your screenshot, I would probably make it specific when something is mapped to the light theme too. Maybe a radio button to select light theme or dark theme. Or even better, a separate checkbox for light theme and dark theme mappings. The implication of just having a check box for dark theme is that if you don't check it, that the mapped theme is used for both light theme and dark theme. And that checking the box limits it to the Eclipse dark theme mapping.

With regard to the background window in your screenshot, you have the following two lines for theme associations.

* "Use the theme 'monokai'"
* Use the theme "Solarized Light" with Eclipse Dark Theme

Again this to me is slightly ambigious. It could mean that use the theme monokai applies to light and dark theme, or it could mean that the theme monokai only applies to an Eclipse light theme. I would prefer this screen be absolutely explicit, either by adding two column to the theme association table (light theme, dark theme) with yes/no true/false checked/unchecked options in the column, or with additional descriptive text for the "Use the theme 'monokai' item" to make it absolutely explicit how it applies to both Eclipse light and dark themes.

**Comment by angelozerr** [comment]
If theme associations is filled like this:

 * Use the theme "Solarized Light" with Eclipse Dark Theme
 * Otherwise use the theme 'Monokai'"

Is it better?

The 2 items are already filled. If there are none associations you will have:

 * Use the theme "Dark" with Eclipse Dark Theme
 * Otherwise use the theme 'Solarized Light'"

Why? Because if you see TextMate / Theme preferences you will see that  'Solarized Light' and 'Dark' are marked as default and 'Dark' is marked as 'dark' type. The dark type is bound with the Eclipse 'Dark' theme.

If you need some UI modification, please draw me some screenshot, it's difficult for me to understand very well your problem.

**Comment by ainslec** [comment]
Yes,  Adding "otherwise" is very good to me.

"Otherwise" makes it clear that the default is "monokai" unless there is a per-eclipse-theme override. Currently, the behaviour for any given theme is not clear. I would structure it like this maybe:

If there is just one mapping default mapping:

"Always use 'Solarized Light theme"

If there are overrides, use your "otherwise" pattern.

"If Eclipse Dark Theme, use textmate theme "Monokai".
"If Eclipse Foo Theme, use textmate theme "Textmate Foo".
"If Eclipse Bar Theme, use textmate theme "Textmate Bar".
"Otherwise use textmate theme "Solarized Light".

**Comment by angelozerr** [comment]
> "If Eclipse Dark Theme, use textmate theme "Monokai".
"If Eclipse Foo Theme, use textmate theme "Textmate Foo".
"If Eclipse Bar Theme, use textmate theme "Textmate Bar".
"Otherwise use textmate theme "Solarized Light".

It was my first idea, manage mapping between eclipse theme and theme for an editor (scope), but code was very complex and configuration too.

That's why I have decided to categorize theme with "Dark" and "Light" (like VSCode). So the theme associations has every time 2 lines: one for Eclipse "Dark" theme and one for other Eclipse themes.

It's not very clean to hard coded "Dark" theme but it simplifies a lot the code and configuration. We will see in the future if it's interesting to configure textmate theme for a given "Light" Eclipse theme (Foo, Bar, etc)

**Comment by ainslec** [comment]
Might I suggest a hybrid then...

Generic mappings for light eclipse themes, generic mappings for dark eclipse themes, and overrides for individual eclipse themes.

In the "theme associations" textbox, document theme mappings like this:

> If Eclipse theme is "foo" explicitly, then use "my theme a",
> If Eclipse theme is "bar" explicitly, then use "my theme b".
> Othewise if Eclipse theme is a dark theme , then use "monokai".
> Otherwise if Eclipse theme is light theme, then use "Solarized light".

It's essentially a textual representation of a switch/case block, but with two defaults - one for light, one for dark. This would be both extremely easy to understand and very powerful.

Or, just have two items:

> If Eclipse theme is a light theme, then use textmate theme "foo".
> If Eclipse theme is a dark theme, then use textmate theme "bar".

The ambiguity is slightly there because Eclipse named an explicit theme "dark", but dark is also a group of themes too. Word choice is very important to be able to understand that the group of Eclipse dark themes is mapping to one particular textmate theme.

**Comment by sebthom** [comment]
Closing because themes set in TextMate preferences are nowadays automatically applied to open editors.
