### ISSUE TITLE
Eclipse color themes support

### ISSUE THREAD

**Issue by timurmazitov** [eclipse/tm4e#180]
Hello!
It will be great to support themes from http://www.eclipsecolorthemes.org.
I mean that user has to change themes in 2 different preference pages now. And tm4e supports only 4 themes. Too few!
I would like to change theme in one place for all eclipse editors.
Thanx

**Comment by mickaelistria** [comment]
I don't think TM4E can depend on eclipse color themes for legal reason. As long as Eclipse Color Theme is not an Eclipse.org project, consuming it in another project like TM4E is hard.

> I mean that user has to change themes in 2 different preference pages now. [...] I would like to change theme in one place for all eclipse editors.


What would be great for TM4E would be to place a listener on the ColorRegistry so that when user changes the background color in any way (directly from the Preferences > General > Text Editor pages, or with Eclipse Color Themes page or whatever), TM4E would be informed and could show a note to the user recommending to switch TM4E theme as well.

> And tm4e supports only 4 themes. Too few!

TM4E would welcome contributions for more themes. Please add those to TM4E and submit pull request.

**Comment by norru** [comment]
The best option at this stage would be to allow custom themes to be added by the user without a rebuild.

**Comment by norru** [comment]
@angelozerr

**Comment by angelozerr** [comment]
> The best option at this stage would be to allow custom themes to be added by the user without a rebuild.

Yes indeed, it was my idea (with TexrMate / Themes preferences) but I had no time to support it. Today theme mus te written in CSS format, but I think it should be better to support theme written with the same format than TextMate grammar.

**Comment by norru** [comment]
Themes written in CSS would be a good first basic implementation while something better is being built.

**Comment by j-ulrich** [comment]
http://www.eclipsecolorthemes.org seems to be offline meanwhile. So I guess this issue can be closed?!
