### ISSUE TITLE
Remove Joni&JCoding from org.eclipse.textmate4e.core

### ISSUE THREAD

**Issue by angelozerr** [eclipse/tm4e#19]
It should be cleaner to remove Joni&JCoding JARS from [org.eclipse.textmate4e.core](https://github.com/angelozerr/textmate.java/tree/master/org.eclipse.textmate4e.core/lib) and use **import packages**.

But there are 2 problems:

 * Joni&JCoding are not OSGi. See https://github.com/jruby/joni/issues/26
 * Joni&JCoding should be in Eclipse orbit.

@mickaelistria have you an idea how to fix thoses 2 problems?

**Comment by mickaelistria** [comment]
Using [EBR](https://github.com/eclipse/ebr), it would be relatively easy to turn those libs into OSGi bundles. Moreover, EBR is the technology Orbit is using, so it would make migration to Orbit smooth.

In order to get to Orbit, we first need to get Textmate4e @eclipse.org and then to open CQs.

Overall, I believe it will be simpler to fix this issue later, once already at Eclipse.org and directly move them to EBR and Orbit simultaneously, with the assistance of Orbit committers.

**Comment by mickaelistria** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=510549 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=510593 for inclusion into Orbit.

**Comment by mickaelistria** [comment]
this one can be closed (I don't have permissions to do so)

**Comment by angelozerr** [comment]
Thanks @mickaelistria for your work about this issue.
