### ISSUE TITLE
Null pointer exception being thrown

### ISSUE THREAD

**Issue by ainsley** [eclipse/tm4e#28]
Using the version from the update site:

![image](https://cloud.githubusercontent.com/assets/201870/21681960/a7a1175e-d349-11e6-941e-a45fc2185a0d.png)

**Comment by angelozerr** [comment]
I know this problem, it means that your grammar is null. I must throw a well exception like "Your grammar is not filled".

Which grammar are you using, samples should work.

**Comment by ainsley** [comment]
OK, I've filled a bit more of the plugin.xml as per the example, but one of the extension points doesn't seem to work:

![image](https://cloud.githubusercontent.com/assets/201870/21682228/58961f04-d34b-11e6-9348-426acda38774.png)

**Comment by angelozerr** [comment]
Your problem is not linked to tm4e. You wish to use GenericEditor which will be available for Oxygen https://github.com/eclipse/eclipse.platform.text/tree/master/org.eclipse.ui.genericeditor

I suggest you that your try with TextEdidor like the FreemarkerEditor sample otherwise please install org.eclipse.ui.genericeditor (if you have problem please post your question to Eclipse.org forum).

**Comment by ainsley** [comment]
So, I don't need that line in my plugin.xml for it to work with my own editor?

**Comment by ainsley** [comment]
OK, starting to work, Thanks. Although the light theme looks bad with my grammar. Am I able to switch to the dark theme via preferences or must it be manually configured via extension point?

**Comment by angelozerr** [comment]
> Am I able to switch to the dark theme via preferences

Yes if you change standard Apperance E4 Theme to Dark, it should change to TextMate dark theme.

If you wish to force your editor to use a given theme, you can do it, but please wait that I finalize this feature.

**Comment by angelozerr** [comment]
> Great, I can confirm I can see a dark-like theme. It's not very good for my particular grammar so being able to specify a particular theme would be essential in my particular use-case, as both of the current themes are not granular enough to be able to distinguish important language features for my particular grammar.

To fix this problem, there are 2 choices:

 * define your own theme, but it means that other languages could have the same problem than you (some CSS could miss)
 * give the capability to inject other CSS declaration to the existing theme for a given language. I think it should be a very good feature.

> Also, having some issues with the style suddenly disappearing on some edits, but I figure you must be aware of those issues so I should be patient and see how this develops.

Could you give me more info please about your problem? It will help me a lot if you could share your project. I could try it and see your problem.

> Performance is generally very good, much better than I was expecting. I'd tried a demo of liclipse before and the performance on large files (5,000 lines+) was regressive. It appears that this project is better at dealing with deltas.

Glad tm4e please you:) I have tried to do like VSCode and colorize the editor when TextMate tokens are available without freezing the editor. Today I have a problem with large file. with complex editor (like my TypeScript editor from typescript.java) which have folding, validation, etc which invalidates the TextPresentation every time. With large file the first part of file is not colorized because TextMate grammar for the full file is not available. I have not found solution for the moment. Hope I will have contribution when TM4E will be host in Eclipse.org https://projects.eclipse.org/projects/technology.tm4e

**Comment by ainsley** [comment]
> give the capability to inject other CSS declaration to the existing theme for a given language. I think it should be a very good feature.

css per file type seems like a good idea.

> Could you give me more info please about your problem? It will help me a lot if you could share your project. I could try it and see your problem.

I'll try to find a way to isolate the files and highlight the problem.

> Today I have a problem with large file. with complex editor (like my TypeScript editor from typescript.java) which have folding, validation, etc which invalidates the TextPresentation every time. With large file the first part of file is not colorized because TextMate grammar for the full file is not available. 

I have not encountered this yet, but I have seen the style go completely missing from a file after a few edits.

**Comment by ainsley** [comment]
An update, it's working very nicely now. Styling exactly as I would expect it to be styled based on the textmate definition as rendered by Atom, Sublime and Visual Studio Code.

That said, I am having some intermittent problems with the entire text being invalidated (losing all highlighting) on certain edits. Not sure when I can feed this back to you in terms of a reproducable bug, but I'll try to isolate it and package up a project that you can use to test with.

**Comment by angelozerr** [comment]
please see my comments https://github.com/angelozerr/textmate.java/issues/31#issuecomment-273271852 to generate tests

**Comment by mickaelistria** [comment]
Would be great to show a more explicit message in case of grammar not found. This NPE doesn't tell much to help debugging.

**Comment by mickaelistria** [comment]
@ainsley Do you think you could contribute addition of a human-friendly message to that stack trace?

**Comment by ainsley** [comment]
@mickaelistria  I certainly could. I'm not sure I'm Eclipse approved for contributions. Is there some sort of agreement I have to sign somehow?

**Comment by mickaelistria** [comment]
Indeed, you first need to have an eclipse.org account (create one [here](https://accounts.eclipse.org/user/register) if you don't have already one), and then approve the Contributor Agreement by clicking on the `    Eclipse Contributor Agreement` tab from your user page and following instructions.
You also need to set the "Sign-Off-By" commit footer. This can be done with EGit by clicking the pen icon above the commit message text area, or by adding the `--signoff` flag to the `git commit` command.
HTH

**Comment by angelozerr** [comment]
> Would be great to show a more explicit message in case of grammar not found. This NPE doesn't tell much to help debugging.

@mickaelistria now this NPE is managed with Assert https://github.com/eclipse/tm4e/blob/master/org.eclipse.tm4e.ui/src/main/java/org/eclipse/tm4e/ui/text/TMPresentationReconciler.java#L171

**Comment by angelozerr** [comment]
@mickaelistria I have added message, don't hesitate to change it if you don't like.

**Comment by mickaelistria** [comment]
Thanks, I think this is perfect! Closing then. Feel free to reopen if I miseed something.
