### ISSUE TITLE
shell script support is missing in latest version of textmate

### ISSUE THREAD

**Issue by raghucssit** [eclipse/tm4e#604]
I have installed the latest version of update site on 4.29 eclipse SDK on Red Hat Linux. I don't see the support for shell script in textmate `Preferences` section and even the editor don't show any syntax highlighting.
Below are the installtion details:
OS: RHEL
Eclipse : 4:29
textmate : https://download.eclipse.org/tm4e/releases/latest/
Installation:
![textmate-latest](https://github.com/eclipse/tm4e/assets/10301131/ab80e378-f69e-4a26-9108-85d18bc5f216)
Missing shell script support:
![shell-support-missing](https://github.com/eclipse/tm4e/assets/10301131/d1d8eb20-e9bf-4d55-93f4-6a106eae35a8)
Also for XML files default editor is not configured like .ts file.
I have not installed sample also.
Question: There is no outline support seen. Is it expected ?

**Comment by mickaelistria** [comment]
Please consider installing shellwax https://github.com/eclipse/shellwax for Bash support in Eclipse IDE.

**Comment by raghucssit** [comment]
> Please consider installing shellwax https://github.com/eclipse/shellwax for Bash support in Eclipse IDE.

We are planning to use single feature/plugin for all the content types like XML, shell etc. Currently we use different plugins for different content types which make our installation bulky. Our plan is to use textmate one stop solution for all.

**Comment by mickaelistria** [comment]
The outline support is provided by language servers usually, not by TextMate grammars.

**Comment by sebthom** [comment]
Shellscript support has never been enabled in tm4e because of issues in the syntax highlighting of the source grammar file. This is visible in the plugin.xml configuration of the language pack.

As @mickaelistria pointed out, outline support is out of scope of tm4e. This plugin only deals with syntax highlighting. I don't think it would be a good decision to only rely on tm4e for all your editing needs as you miss out on all the useful features provided by a language specific language server such as auto completion, semantic highlighting, refactoring support, etc. so for shell support you should additionally rely on https://github.com/eclipse/shellwax for web technologies on https://github.com/eclipse/wildwebdeveloper, etc...

**Comment by raghucssit** [comment]
@sebthom are the issues with syntax highlighting in shell script severe ? Please share samples of the issues if avaiable. I will try to add shell script support by adding new configuration in preferences. If i have some idea of issues it will help me when i try it.

**Comment by sebthom** [comment]
Shell script syntax highlighting is enabled in the latest snapshot version of TM4E

**Comment by sebthom** [comment]
@akurtakov We are sourcing all grammars from the [vscode extensions repo](https://github.com/microsoft/vscode/tree/main/extensions) after we received approval for updates from the IP team. I think best (but slowest) would be if you contribute changes upstream at https://github.com/jeff-hykin/better-shell-syntax which is where vscode itself syncs from.
