### ISSUE TITLE
SWT, Swing, or JavaFX clients?

### ISSUE THREAD

**Issue by ainslec** [eclipse/tm4e#75]
Do you know if anyone is working on a Swing, SWT (non Eclipse) or JavaFX component that can sit atop of this library?

I attempted to integrate TM4E with RSyntaxTextArea but my gut feeling is that they were incompatible. 

Looking at RSyntaxTextArea's documentation is it the opinion of the developers that it is possible to hook up TM4E efficiently? If I know it is is possible, I'll go back and take a second look.

**Comment by mickaelistria** [comment]
The org.eclipse.tm4e.core library doesn't have any dependency on Eclipse, so you should be able to use it in any context. I think the approach to use the API is to implement the "AbstractTMModel" with your UI specific stuff, and register a listener on the model. Then you'll receive the result of TextMate parsing for the file and you can decide how to use it in order to colorize the text.

**Comment by angelozerr** [comment]
@ainsley I had created an issue at https://github.com/bobbylight/RSyntaxTextArea/issues/213 and I hope @bobbylight will have time to study how to integrate TM4E with RSyntaxTextArea. 

@boniatillo-com I know you have worked with RSyntaxTextArea with tern.java, is there any chance that you could help us for this issue?

**Comment by mickaelistria** [comment]
I'm closing this one as the question got answer, and nothing seems actionable in TM4E from the current state.
If you have more specific and concrete enhancement proposals, please open new tickets.
