### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by jmozmoz** [eclipse/tm4e#806]
Eclipse "terminated" the PTP (Parallel Tools Platform) project, including the support for Fortran (https://www.eclipse.org/projects/tools/reviews.php, search for November 29, 2023, [Eclipse Parallel Tools Platform Eclipse Parallel Tools Platform (PTP) Termination](https://projects.eclipse.org/projects/tools.ptp/reviews/termination-review), the link itself seems to not exist any more).

There is a project to support Fortran in VS Code: https://github.com/fortran-lang/vscode-fortran-support

Just an idea: Could support for Fortran also be added to TM4e based on that project?

**Comment by angelozerr** [comment]
Adding TextMate and too language configuration https://github.com/fortran-lang/vscode-fortran-support/blob/main/language-configuration.json to benefit from auto close, etc

**Comment by sebthom** [comment]
I'm not in favor of adding more languages from other sources to the TM4E language pack due to the required Eclipse IP review process for each and every update. Occasionally updating all languages from https://github.com/microsoft/vscode/tree/main/extensions in one go is fine, but having to do the same for more languages from other sources is cumbersome.

Btw. I added Fortran syntax highlighting to https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin where upstream updates are automatically included and are immediately available.

**Comment by sebthom** [comment]
TM4E provides the ability to perform syntax highlighting using textmate grammars. It comes with a language pack that contains all textmate grammars that are copied from the vscode source repo. so it supports highlighting the same languages out of the box as vscode. tm4e provides an extension point that allows other plugins such as the extra-syntax-highlighting-eclipse-plugin to install additional textmate grammars for other languages. so they extra-syntax-highlighting-eclipse-plugin requires tm4e which does the actual syntax highlighting.

if you want more than just syntax highlighting such as auto completion, refactoring, code generation, syntax validation,... an additional plugin needs to providea language server that is registered with the lsp4e plugin. such a plugin would for example be the wildwebdeveloper plugin offering typescript language support.

**Comment by sebthom** [comment]
I am going to close the issue as not planned for now. Main hurdle for me is the IP review process for each update requiring a separatly filled out issue and which takes several weeks for approval. The extra-syntax-highlighting-eclipse-plugin is not bound to this process and can be updated timely and with way less effort.
